name: 'jaffle_shop'
version: '1.0.0'

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +hours_to_expiration: |
    {%- if target.name == "dev" -%} 72
    {%- elif target.name == "prod" -%} null
    {%- else -%} invalid_project
    {%- endif -%}
  jaffle_shop:
    +project: |
      {%- if target.name == "dev" -%} dbt-project-463320
      {%- elif target.name == "prod" -%} dbt-project-prod-463419
      {%- else -%} invalid_project
      {%- endif -%}
    +dataset: |
      +project: |
      {%- if target.name == "dev" -%} default_dev
      {%- elif target.name == "prod" -%} default_prod
      {%- else -%} invalid_project
      {%- endif -%}
    +persist_docs:
      relation: true
      column: true
    
    staging:
      +materialized: view
      dataset: staging
      
