jaffle_shop:
  
  target: "{{ env_var('TARGET') }}"
  
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dbt-project-463320
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      # keyfile: ~/Downloads/dbt-user-creds.json
      location: US
      # method: service-account
      priority: interactive
      threads: 4
      
  
