version: 2

models: 
  - name: stg_customers
    description: Contains Jaffle shop customer data
    config:
      alias: customers
    columns:
      - name: customer_id
        description: Unique Customer ID
        tests:
          - not_null
          - unique
      - name: first_name
        description: Customer's first name
      - name: last_name
        description: Customer's last name

  - name: stg_orders
    description: Contains Jaffle shop orders data
    config:
      alias: orders
    columns:
      - name: order_id
        description: Unique order ID
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique Customer ID
        tests:
          - not_null
      - name: order_date
        description: Order creation date
        tests:
          - not_null
      - name: status
        description: Order status
        tests:
          - not_null
        

      